FreshMart/Models/Product.cs
using System.ComponentModel;

namespace FreshMart.Models
{
    public class Product
    {
        public int Id { get; set; } 
        public double Price { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public Category? Category { get; set; }
        public int SupplierId { get; set; }
        public Supplier? Supplier { get; set; }

        public ICollection<CartItem>? CartItems { get; set; }
    }
}

FreshMart/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FreshMart.Models;
using FreshMart.Data;
using FreshMart.Repositories.Interfaces;
using FreshMart.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace FreshMart.Controllers
{
    [Authorize(Roles = "Administrator,User")]
    public class CategoriesController : Controller
    {
        private ICategoryService _categoryService;

        public CategoriesController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        // GET: Categories
        [AllowAnonymous]
        public IActionResult Index()
        {
            var categories = _categoryService.GetAllCategories();
            return View(categories);
        }

        //GET: Categories/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = _categoryService.GetCategoryById(id.Value);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        //GET: Categories/Create
        [Authorize (Roles = "Administrator")]
         public IActionResult Create()
        {
            return View();
        }

        //POST: Categories/Create
        //To protect from overposting attacks, enable the specific properties you want to bind to.
        //For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create([Bind("Id,Name,Description")] Category category)
         {
            if (ModelState.IsValid)
            {
                _categoryService.AddCategory(category);
                return RedirectToAction(nameof(Index));
            }
            return View(category);
         }

        // GET: Categories/Edit/5
        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = _categoryService.GetCategoryById(id.Value);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Edit/5
        //  To protect from overposting attacks, enable the specific properties you want to bind to.
        //  For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(int id, [Bind("Id,Name,Description")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _categoryService.UpdateCategory(category);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_categoryService.CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = _categoryService.GetCategoryById(id.Value);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public IActionResult DeleteConfirmed(int id)
        {
            _categoryService.DeleteCategory(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

FreshMart/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FreshMart.Models;
using FreshMart.Data;
using FreshMart.Repositories.Interfaces;
using FreshMart.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace FreshMart.Controllers
{
    [Authorize(Roles = "Administrator,User")]
    public class ProductsController : Controller
    {
        private IProductService _productService;
        private ICategoryService _categoryService;

        public ProductsController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }

        // GET: Products
        [AllowAnonymous]
        public IActionResult Index(string productName)
        {
            var products = _productService.GetAllProducts();
            if (String.IsNullOrEmpty(productName))
            {
                return View(products);
            } else
            {
                var searchItems = _productService.GetSearchedProducts(productName);
                return View(searchItems);
            }
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult FilteredByCategory(int categoryId)
        {
            // Retrieve products based on the categoryId and pass them to the view
            var products = _productService.GetProductsByCategoryId(categoryId);
            return View(products);
        }


        // GET: Products/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = _productService.GetProductAndRelatedById(id.Value);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            var categories = _productService.GetAllCategories();
            var suppliers = _productService.GetAllSuppliers();
            ViewData["CategoryId"] = new SelectList(categories, "Id", "Name");
            ViewData["SupplierId"] = new SelectList(suppliers, "Id", "Name");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create([Bind("Id,Price,Name,CategoryId,SupplierId")] Product product)
        {
            if (ModelState.IsValid)
            {
                var category = _categoryService.GetCategoryById(product.CategoryId);
                product.Category = category;
                _productService.AddProduct(product);
                return RedirectToAction(nameof(Index));
            }
            var categories = _productService.GetAllCategories();
            var suppliers = _productService.GetAllSuppliers();
            ViewData["CategoryId"] = new SelectList(categories, "Id", "Name", product.CategoryId);
            ViewData["SupplierId"] = new SelectList(suppliers, "Id", "Name", product.SupplierId);
            return View(product);
        }

        // GET: Products/Edit/5
        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = _productService.GetProductById(id.Value);

            if (product == null)
            {
                return NotFound();
            }

            var categories = _productService.GetAllCategories();
            var suppliers = _productService.GetAllSuppliers();
            ViewData["CategoryId"] = new SelectList(categories, "Id", "Name", product.CategoryId);
            ViewData["SupplierId"] = new SelectList(suppliers, "Id", "Name", product.SupplierId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(int id, [Bind("Id,Price,Name,CategoryId,SupplierId")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _productService.UpdateProduct(product);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_productService.ProductExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var categories = _productService.GetAllCategories();
            var suppliers = _productService.GetAllSuppliers();
            ViewData["CategoryId"] = new SelectList(categories, "Id", "Name", product.CategoryId);
            ViewData["SupplierId"] = new SelectList(suppliers, "Id", "Name", product.SupplierId);
            return View(product);
        }

        // GET: Products/Delete/5
        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = _productService.GetProductAndRelatedById(id.Value);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public IActionResult DeleteConfirmed(int id)
        {
            _productService.DeleteProduct(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

FreshMart/Controllers/ShoppingCartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FreshMart.Data;
using FreshMart.Models;
using FreshMart.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using FreshMart.Services;

namespace FreshMart.Controllers
{
    [Authorize(Roles = "Administrator,User")]
    public class ShoppingCartsController : Controller
    {
        private IShoppingCartService _shoppingCartService;
        private IProductService _productService;
        private ICartItemService _cartItemService;

        public ShoppingCartsController(
            IShoppingCartService shoppingCartService, 
            IProductService productService,
            ICartItemService cartItemService)
        {
            _shoppingCartService = shoppingCartService;
            _productService = productService;
            _cartItemService = cartItemService;
        }

        // GET: ShoppingCarts
        public IActionResult Index()
        {
            var shoppingCart = _shoppingCartService.GetExistingShoppingCart();
            _shoppingCartService.LoadCartCollection(shoppingCart);
            return View(shoppingCart);
        }


        [HttpPost]
        public IActionResult AddToCart(int productId, int quantity)
        {
            var shoppingCart = _shoppingCartService.GetExistingShoppingCart();

            var product = _productService.GetProductById(productId);
            var cartItem = new CartItem
            {
                Quantity = quantity,
                ProductId = productId,
                Product = product,
                ShoppingCartId = shoppingCart.Id,
                ShoppingCart = shoppingCart
            };
            _shoppingCartService.AddCartItem(shoppingCart, cartItem);

            return RedirectToAction("Index");
        }


        // GET: ShoppingCarts/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoppingCart = _shoppingCartService.GetShoppingCartById(id.Value);

            if (shoppingCart == null)
            {
                return NotFound();
            }

            return View(shoppingCart);
        }

        // GET: ShoppingCarts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ShoppingCarts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Size,Ammount")] ShoppingCart shoppingCart)
        {
            if (ModelState.IsValid)
            {
                _shoppingCartService.AddShoppingCart(shoppingCart);
                return RedirectToAction(nameof(Index));
            }
            return View(shoppingCart);
        }

        // GET: ShoppingCarts/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoppingCart = _shoppingCartService.GetShoppingCartById(id.Value);

            if (shoppingCart == null)
            {
                return NotFound();
            }
            return View(shoppingCart);
        }

        // POST: ShoppingCarts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Size,Ammount")] ShoppingCart shoppingCart)
        {
            if (id != shoppingCart.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _shoppingCartService.UpdateShoppingCart(shoppingCart);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_shoppingCartService.ShoppingCartExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(shoppingCart);
        }

        // GET: ShoppingCarts/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoppingCart = _shoppingCartService.GetShoppingCartById(id.Value);

            if (shoppingCart == null)
            {
                return NotFound();
            }

            return View(shoppingCart);
        }

        // POST: ShoppingCarts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _shoppingCartService.DeleteShoppingCart(id);
            
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCartItem(int cartItemId)
        {
            var cartItem = _cartItemService.GetCartItemById(cartItemId);

            if (cartItem != null)
            {
                var shoppingCart = _shoppingCartService.GetShoppingCartById(cartItem.ShoppingCartId);
                if (shoppingCart != null)
                {
                    _shoppingCartService.removeCartItem(shoppingCart, cartItem);
                    //_cartItemService.DeleteCartItem(cartItem); 
                }
            }

            return RedirectToAction("Index");
        }
    }
}

FreshMart/Views/Products/Create.cshtml
@model FreshMart.Models.Product

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Supplier" class="control-label"></label>
                <select asp-for="SupplierId" class ="form-control" asp-items="ViewBag.SupplierId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-primary action-btn">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FreshMart/Views/Products/Delete.cshtml
@model FreshMart.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Supplier)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Supplier.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-primary action-btn">Back to List</a>
    </form>
</div>

FreshMart/Views/Products/Details.cshtml
@model FreshMart.Models.Product

@{
    ViewData["Title"] = "Details";
    bool isAdmin = User.IsInRole("Administrator");
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Supplier)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Supplier.Name)
        </dd>
    </dl>
</div>
<div>
    @if (isAdmin)
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary action-btn">Edit</a>
    }
    
    <a asp-action="Index" class="btn btn-primary action-btn">Back to List</a>
</div>

FreshMart/Views/Products/Edit.cshtml
@model FreshMart.Models.Product

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Supplier" class="control-label"></label>
                <select asp-for="SupplierId" class="form-control" asp-items="ViewBag.SupplierId"></select>
                <span asp-validation-for="SupplierId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-primary action-btn">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FreshMart/Views/Products/FilteredByCategory.cshtml
@model IEnumerable<FreshMart.Models.Product>

@{
    ViewData["Title"] = "Filtered By Category";
    bool isAdmin = User.IsInRole("Administrator");
    bool isUser = User.IsInRole("User");
}

<h1>Products of the selected category</h1>

<a class="btn btn-primary" href="@Url.Action("Index", "Categories")">Back to Categories</a>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Supplier)
            </th>
            <th>
                Quantity
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Supplier.Name)
                </td>
                <td>
                    <div class="btn-group">
                        <form method="post" action="@Url.Action("AddToCart", "ShoppingCarts")" style="display: inline;">
                            <div class="input-group">
                                <input type="hidden" name="productId" value="@item.Id" />
                                <input class="form-control form-control-sm" type="number" name="quantity" value="1" min="1" style="width: 60px; height: 10px" />
                                <div class="form-action-button" style="margin-left: 10px;">
                                    <button class="btn btn-danger" type="submit">Add to Cart</button>
                                </div>
                            </div>
                        </form>
                        @if (isAdmin)
                        {
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        }
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

FreshMart/Views/Products/Index.cshtml
@model IEnumerable<FreshMart.Models.Product>

@{
    ViewData["Title"] = "Index";
    bool isAdmin = User.IsInRole("Administrator");
    bool isUser = User.IsInRole("User");
}

<h1>Products</h1>
@if (isAdmin)
{
    <a asp-action="Create">Create New</a>
}
<form asp-action="Index">
    <div class="input-group md-form form-control-sm form-2 pl-0">
        <input name="productName" class="form-control my-0 py-1 table-bordered" type="text" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
            <button class="btn btn-outline-success" id="search-button">Search</button>
        </div>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Supplier)
            </th>
            <th>
                Quantity
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Supplier.Name)
            </td>
            <td>
                <div class="btn-group">
                    <form method="post" action="@Url.Action("AddToCart", "ShoppingCarts")" style="display: inline;">
                        <div class="input-group">
                            <input type="hidden" name="productId" value="@item.Id" />
                            <input class="form-control form-control-sm" type="number" name="quantity" value="1" min="1" style="width: 60px; height: 10px" />
                             <div class="form-action-button" style="margin-left: 10px;">
                                <button class="btn btn-danger" type="submit">Add to Cart</button>
                            </div>
                        </div>
                    </form>
                    </div>
                        @if(isUser || isAdmin)
                        {
                            <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary action-btn">Details</a>

                        } else
                        @if (isAdmin){
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary action-btn">Edit</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-primary action-btn">Delete</a>
                        }
            </td>
        </tr>
}
    </tbody>
</table>